#-*- coding:utf-8 -*-
__author__ = "Neil"
__time__ = "2017/10/31 23:49"

from Tkinter import *
root=Tk()
root.title("网络扫描器")
root.geometry("400x420")

result= Label(root,text = '扫描结果:',font=("",12))
result.grid(row=3,column=3,sticky=W,padx=5)
result_list=Listbox(root,height=7)
result_list.grid(row=4,column=3,padx=10,rowspan=7)

arp_title= Label(root,text = 'arp扫描',font=("",13))
arp_mac_label= Label(root,text = 'mac 地址',font=("",10))
arp_ip_label= Label(root,text = 'ip 地址',font=("",10))
arp_title.grid(row=0,column=1)
arp_ip=Entry(root)
arp_mac=Entry(root)
arp_ip_label.grid(row=1,column=0)
arp_mac_label.grid(row=2,column=0)
arp_ip.grid(row=1,column=1,pady=5)
arp_mac.grid(row=2,column=1,pady=5)
# arp_list=Listbox(root,height=3)
# arp_list.grid(row=2,column=3,padx=10,rowspan=2)
arp_button=Button(root,text="开始arp扫描")
arp_button.grid(row=3,column=1,sticky=W)


tcp_title= Label(root,text = 'tcp端口扫描',font=("",13))
#tcp_result= Label(root,text = '扫描结果:',font=("",12))
tcp_ip_label= Label(root,text = 'ip 地址',font=("",10))
tcp_port_label= Label(root,text = '端口号',font=("",10))
#tcp_result.grid(row=1,column=3,sticky=W,padx=5)
tcp_title.grid(row=5,column=1)
tcp_ip=Entry(root)
tcp_port=Entry(root)
tcp_ip_label.grid(row=6,column=0)
tcp_port_label.grid(row=7,column=0)
tcp_ip.grid(row=6,column=1,pady=5)
tcp_port.grid(row=7,column=1,pady=5)
# arp_list=Listbox(root,height=3)
# arp_list.grid(row=2,column=3,padx=10,rowspan=2)
tcp_button=Button(root,text="开始端口扫描")
tcp_button.grid(row=8,column=1,sticky=W)

sql_title= Label(root,text = '应用层漏洞扫描',font=("",13))
#tcp_result= Label(root,text = '扫描结果:',font=("",12))
sql_url_label= Label(root,text = 'url 地址',font=("",10))
sql_post_label= Label(root,text = '表单参数',font=("",10))
sql_cookie_label= Label(root,text = 'Cookie',font=("",10))
#tcp_result.grid(row=1,column=3,sticky=W,padx=5)
sql_title.grid(row=10,column=1)
sql_url=Entry(root)
sql_post=Entry(root)
sql_cookie=Entry(root)
sql_url_label.grid(row=11,column=0)
sql_post_label.grid(row=12,column=0)
sql_cookie_label.grid(row=13,column=0)
sql_url.grid(row=11,column=1,pady=5)
sql_post.grid(row=12,column=1,pady=5)
sql_cookie.grid(row=13,column=1,pady=5)
# arp_list=Listbox(root,height=3)
# arp_list.grid(row=2,column=3,padx=10,rowspan=2)
sql_button=Button(root,text="开始sql漏洞扫描")
xss_button=Button(root,text="开始xss漏洞扫描")
xss_button.grid(row=15,column=1,sticky=W)
sql_button.grid(row=14,column=1,sticky=W)


mainloop()
